version: '3.1'

services:

  postgresql:
    image: postgres:15.1
    restart: unless-stopped
    command:
      - -c
      - wal_level=logical
      - -c
      - wal_compression=on
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecr3t
    volumes:
      - ./sample:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - local

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1.18.0
    ports:
      - 6432:6432
    profiles:
      - pgbouncer
    environment:
      POSTGRESQL_HOST: postgresql
      # PGBOUNCER_AUTH_TYPE: trust
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: SuperSecr3t
      PGBOUNCER_DATABASE: "*"
      PGBOUNCER_POOL_MODE: session # session | transaction | statement
      PGBOUNCER_MAX_CLIENT_CONN: 20
      PGBOUNCER_MAX_DB_CONNECTIONS: 10
      PGBOUNCER_DEFAULT_POOL_SIZE: 50
      PGBOUNCER_IGNORE_STARTUP_PARAMETERS: extra_float_digits
      PGBOUNCER_AUTH_USER: postgres
    networks:
      - local

volumes:
  postgres_data:

networks:
  local:
    external: true
